services:
  jenkins:
    container_name: ${CONTAINER_NAME}
    image: jenkins/jenkins:2.452.2-lts
    restart: always
    privileged: true
    user: root
    ports:
      - ${PANEL_APP_PORT_HTTP}:8080
    environment:
      - JENKINS_OPTS=--prefix=${JENKINS_PREFIX}
      - JENKINS_ARGS=--prefix=${JENKINS_PREFIX}
    volumes:
      - ./data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKER_BINARY}:${DOCKER_BINARY}
      - ${DIR_JDKS}:/var/jdks
      - ${DIR_ANDROID_SDK}:/var/android_sdk
    networks:
      - 1panel-network
    labels:
      createdBy: "Apps"
networks:
  1panel-network:
    external: true
